PATH should be set in .profile rather than .bashrc, otherwise things run from gnome (emacs, browsers, etc) don't get the right path. Comment out a load of solarflare stuff that's not really needed any more.

diff --git a/dotbashrc b/dotbashrc
--- a/dotbashrc
+++ b/dotbashrc
@@ -8,6 +8,8 @@
 # home machines!
 #[ -z "$PS1" ] && return
 
+# This is not the right place to set the PATH. Do that in ~/.profile
+
 # check the window size after each command and, if necessary,
 # update the values of LINES and COLUMNS.
 shopt -s checkwinsize
@@ -140,7 +142,7 @@ function fndg
 
 alias h='history 10'
 
-PATH=$PATH:~/bin
+
 
 alias unisondesktop2dellmini='unison /home/john/Desktop/unison ssh://john@dell-mini//home/john/Desktop/unison'
 alias unisondesktop2mini2='unison /home/john/Desktop/unison ssh://john@mini-2//home/john/Desktop/unison'
@@ -163,91 +165,91 @@ function mktags
 
 
 
-#stuff added for solarflare build
+# #stuff added for solarflare build
 
-PATH=$PATH:/home/jla/myco/chip_test/scripts
-PATH=$PATH:/projects/huntington_A0/Release/ef10-tools/v1_14/bin/
-export PATH
+# #PATH=$PATH:/home/jla/myco/chip_test/scripts
+# #PATH=$PATH:/projects/huntington_A0/Release/ef10-tools/v1_14/bin/
+# #export PATH
 
-export PROJ_DIR=/projects/huntington_A0/Work/$USER/hunt/lom
+# #export PROJ_DIR=/projects/huntington_A0/Work/$USER/hunt/lom
 
-# solarflare productivity aliases
+# # solarflare productivity aliases
 
-# this one is for running continuous sims. The killer window will destroy all processes on anvil
-# shortly after the screensaver activates, so that you don't leave expensive sims running over lunch 
-alias anvilicious="gnome-terminal --geometry=110x40+1200+10 --profile anvil \
---tab --title=Desktop --profile default \
---tab --title=anvil \
---tab --title=uart1 \
---tab --title=hwlog1  \
---tab --title=cosim1 \
---tab --title=uart2 \
---tab --title=hwlog2 \
---tab --title=cosim2 \
---tab --title=killer -e '/home/jla/hobby-code/screensaveridle.pl'"
+# # this one is for running continuous sims. The killer window will destroy all processes on anvil
+# # shortly after the screensaver activates, so that you don't leave expensive sims running over lunch 
+# alias anvilicious="gnome-terminal --geometry=110x40+1200+10 --profile anvil \
+# --tab --title=Desktop --profile default \
+# --tab --title=anvil \
+# --tab --title=uart1 \
+# --tab --title=hwlog1  \
+# --tab --title=cosim1 \
+# --tab --title=uart2 \
+# --tab --title=hwlog2 \
+# --tab --title=cosim2 \
+# --tab --title=killer -e '/home/jla/hobby-code/screensaveridle.pl'"
 
-# usual configuration for running jlahacks, with simulator, uart, hwlog, and verdi windows, plus a back up sim 
-alias anvilsims="gnome-terminal --geometry=88x40+1200+10 --profile anvil \
---tab --title=sim1 \
---tab --title=uart1  \
---tab --title=hwlog1 \
---tab --title=verdi1 \
---tab --title=sim2 \
---tab --title=uart2 \
---tab --title=hwlog2 \
---tab --title=verdi2 \
-"
+# # usual configuration for running jlahacks, with simulator, uart, hwlog, and verdi windows, plus a back up sim 
+# alias anvilsims="gnome-terminal --geometry=88x40+1200+10 --profile anvil \
+# --tab --title=sim1 \
+# --tab --title=uart1  \
+# --tab --title=hwlog1 \
+# --tab --title=verdi1 \
+# --tab --title=sim2 \
+# --tab --title=uart2 \
+# --tab --title=hwlog2 \
+# --tab --title=verdi2 \
+# "
 
-# occasional need to run four in parallel
-alias anvil4sims="gnome-terminal --geometry=88x40+1200+10 --profile anvil \
---tab --title=sim1 \
---tab --title=hwlog1 \
---tab --title=sim2 \
---tab --title=hwlog2 \
---tab --title=sim3 \
---tab --title=hwlog3 \
---tab --title=sim4 \
---tab --title=hwlog4 \
-"
+# # occasional need to run four in parallel
+# alias anvil4sims="gnome-terminal --geometry=88x40+1200+10 --profile anvil \
+# --tab --title=sim1 \
+# --tab --title=hwlog1 \
+# --tab --title=sim2 \
+# --tab --title=hwlog2 \
+# --tab --title=sim3 \
+# --tab --title=hwlog3 \
+# --tab --title=sim4 \
+# --tab --title=hwlog4 \
+# "
 
-# various windows for building different versions of the hardware
-alias anvilcompilers="gnome-terminal --geometry=122x40+1200+10 --profile anviltcsh \
---tab --title=magicmipson\ svn \
---tab --title=krserdesonly\ svn \
---tab --title=serdes\ svn \
---tab --title=Desktop --profile default \
---tab --title=gitsvnhunt --profile default \
-"
-#--tab --title=mbistfastfuncfast\ svn \
-#--tab --title=magicmipson\ svngit \
-#--tab --title=mbistfastfuncfast\ svngit\
-#--tab --title=magicmipson\ buildintree \
+# # various windows for building different versions of the hardware
+# alias anvilcompilers="gnome-terminal --geometry=122x40+1200+10 --profile anviltcsh \
+# --tab --title=magicmipson\ svn \
+# --tab --title=krserdesonly\ svn \
+# --tab --title=serdes\ svn \
+# --tab --title=Desktop --profile default \
+# --tab --title=gitsvnhunt --profile default \
+# "
+# #--tab --title=mbistfastfuncfast\ svn \
+# #--tab --title=magicmipson\ svngit \
+# #--tab --title=mbistfastfuncfast\ svngit\
+# #--tab --title=magicmipson\ buildintree \
 
-# for running continuous sims, with their /9p directories pointed at chip_test so that you can recompile tests without having to restart the sims
-alias cosim1="export COSIM_IDENTITY=jla  && time ~/myco/chip_test/src/tools/cosim/esnap --load --passthrough ~/myco/chip_test"
-alias cosim2="export COSIM_IDENTITY=jla2 && time ~/myco/chip_test/src/tools/cosim/esnap --load --passthrough ~/myco/chip_test"
-
-
-alias hwlog1="reset && clear && date && ls -al /local/scratch/esnap_jla/hwlog  ; tail -n 100000 -F /local/scratch/esnap_jla/hwlog"
-alias hwlog2="reset && clear && date && ls -al /local/scratch/esnap_jla2/hwlog ; tail -n 100000 -F /local/scratch/esnap_jla2/hwlog"
-alias hwlog3="reset && clear && date && ls -al /local/scratch/esnap_jla3/hwlog ; tail -n 100000 -F /local/scratch/esnap_jla3/hwlog"
-alias hwlog4="reset && clear && date && ls -al /local/scratch/esnap_jla4/hwlog ; tail -n 100000 -F /local/scratch/esnap_jla4/hwlog"
-
-alias uart1="reset && clear && date && ls -al /local/scratch/esnap_jla/uart0.log  ; tail -n 100000 -F /local/scratch/esnap_jla/uart0.log"
-alias uart2="reset && clear && date && ls -al /local/scratch/esnap_jla2/uart0.log ; tail -n 100000 -F /local/scratch/esnap_jla2/uart0.log"
-alias uart3="reset && clear && date && ls -al /local/scratch/esnap_jla3/uart0.log ; tail -n 100000 -F /local/scratch/esnap_jla3/uart0.log"
-alias uart4="reset && clear && date && ls -al /local/scratch/esnap_jla4/uart0.log ; tail -n 100000 -F /local/scratch/esnap_jla4/uart0.log"
-
-# anvil process control
-alias anvkill="ssh anvil ps -ef | grep jla; ssh anvil pkill -9 -u jla ; ssh anvil ps -ef | grep jla"
-alias anvcheck="ssh anvil ps -ef | grep jla"
+# # for running continuous sims, with their /9p directories pointed at chip_test so that you can recompile tests without having to restart the sims
+# alias cosim1="export COSIM_IDENTITY=jla  && time ~/myco/chip_test/src/tools/cosim/esnap --load --passthrough ~/myco/chip_test"
+# alias cosim2="export COSIM_IDENTITY=jla2 && time ~/myco/chip_test/src/tools/cosim/esnap --load --passthrough ~/myco/chip_test"
 
 
-alias vcstatuses="echo ~/myco/firmwaresrc && cd ~/myco/firmwaresrc && hg status && echo not checking outgoing ; echo ~/myco/chip_test && cd ~/myco/chip_test/ && hg status && echo not checking outgoing ; echo ~/hobby-code && cd ~/hobby-code/ && git status && git log origin/solarflare..solarflare ; echo ~/Desktop/solarflare && cd ~/Desktop/solarflare && hg status && hg outgoing ; cd /projects/huntington_A0/Work/jla/gitsvnhunt && git status && git log remotes/trunk..HEAD "
+# alias hwlog1="reset && clear && date && ls -al /local/scratch/esnap_jla/hwlog  ; tail -n 100000 -F /local/scratch/esnap_jla/hwlog"
+# alias hwlog2="reset && clear && date && ls -al /local/scratch/esnap_jla2/hwlog ; tail -n 100000 -F /local/scratch/esnap_jla2/hwlog"
+# alias hwlog3="reset && clear && date && ls -al /local/scratch/esnap_jla3/hwlog ; tail -n 100000 -F /local/scratch/esnap_jla3/hwlog"
+# alias hwlog4="reset && clear && date && ls -al /local/scratch/esnap_jla4/hwlog ; tail -n 100000 -F /local/scratch/esnap_jla4/hwlog"
 
-alias verdi1="tcsh -c 'cd /projects/huntington_A0/Work/jla/hunt/lom ; verdi -lib  /projects/huntington_A0/Work/jla/hunt/lom/dv/blk/farmi_lite/sim/deblib -top 'platm_tb_top' -nologo -ssf /local/scratch/esnap_jla/tb_top.fsdb -sswr ~/myco/firmwaresrc/favourite-signals.rc'"
+# alias uart1="reset && clear && date && ls -al /local/scratch/esnap_jla/uart0.log  ; tail -n 100000 -F /local/scratch/esnap_jla/uart0.log"
+# alias uart2="reset && clear && date && ls -al /local/scratch/esnap_jla2/uart0.log ; tail -n 100000 -F /local/scratch/esnap_jla2/uart0.log"
+# alias uart3="reset && clear && date && ls -al /local/scratch/esnap_jla3/uart0.log ; tail -n 100000 -F /local/scratch/esnap_jla3/uart0.log"
+# alias uart4="reset && clear && date && ls -al /local/scratch/esnap_jla4/uart0.log ; tail -n 100000 -F /local/scratch/esnap_jla4/uart0.log"
 
-alias verdi2="tcsh -c 'cd /projects/huntington_A0/Work/jla/hunt/lom ; verdi -lib  /projects/huntington_A0/Work/jla/hunt/lom/dv/blk/farmi_lite/sim/deblib -top 'platm_tb_top' -nologo -ssf /local/scratch/esnap_jla2/tb_top.fsdb -sswr ~/myco/firmwaresrc/favourite-signals.rc'"
+# # anvil process control
+# alias anvkill="ssh anvil ps -ef | grep jla; ssh anvil pkill -9 -u jla ; ssh anvil ps -ef | grep jla"
+# alias anvcheck="ssh anvil ps -ef | grep jla"
+
+
+# alias vcstatuses="echo ~/myco/firmwaresrc && cd ~/myco/firmwaresrc && hg status && echo not checking outgoing ; echo ~/myco/chip_test && cd ~/myco/chip_test/ && hg status && echo not checking outgoing ; echo ~/hobby-code && cd ~/hobby-code/ && git status && git log origin/solarflare..solarflare ; echo ~/Desktop/solarflare && cd ~/Desktop/solarflare && hg status && hg outgoing ; cd /projects/huntington_A0/Work/jla/gitsvnhunt && git status && git log remotes/trunk..HEAD "
+
+# alias verdi1="tcsh -c 'cd /projects/huntington_A0/Work/jla/hunt/lom ; verdi -lib  /projects/huntington_A0/Work/jla/hunt/lom/dv/blk/farmi_lite/sim/deblib -top 'platm_tb_top' -nologo -ssf /local/scratch/esnap_jla/tb_top.fsdb -sswr ~/myco/firmwaresrc/favourite-signals.rc'"
+
+# alias verdi2="tcsh -c 'cd /projects/huntington_A0/Work/jla/hunt/lom ; verdi -lib  /projects/huntington_A0/Work/jla/hunt/lom/dv/blk/farmi_lite/sim/deblib -top 'platm_tb_top' -nologo -ssf /local/scratch/esnap_jla2/tb_top.fsdb -sswr ~/myco/firmwaresrc/favourite-signals.rc'"
 
 alias githbc='git --git-dir=/home/jla/hobby-code/.git --work-tree=/home/jla/hobby-code'
 
@@ -255,113 +257,111 @@ alias hgcleanforce='hg status --ignored --unknown | awk  "( \$1 == \"?\" ) || ( 
 alias hgcleandryrun='hg status --ignored --unknown | awk  "( \$1 == \"?\" ) || ( \$1 == \"I\") { print \$2 }" '
 
 
-function backupresults
-{
-    V="$(date +'%F%R')"
-    I=$1
-    EXT=$2
-    BACKUPDIR="$HOME/esnapshots/${V}esnap_${I}_${EXT}"
-    if [ -d ${BACKUPDIR} ] ; then 
-      echo "collision!"
-    else
-      mkdir -p ${BACKUPDIR}
-      cp -a /local/scratch/esnap_${I}/*  ${BACKUPDIR}
-    fi
-}
+# function backupresults
+# {
+#     V="$(date +'%F%R')"
+#     I=$1
+#     EXT=$2
+#     BACKUPDIR="$HOME/esnapshots/${V}esnap_${I}_${EXT}"
+#     if [ -d ${BACKUPDIR} ] ; then 
+#       echo "collision!"
+#     else
+#       mkdir -p ${BACKUPDIR}
+#       cp -a /local/scratch/esnap_${I}/*  ${BACKUPDIR}
+#     fi
+# }
 
-function onerunsimtorulethemall
-{
-    reset
-    clear
-    date 
+# function onerunsimtorulethemall
+# {
+#     reset
+#     clear
+#     date 
 
-    TMPFILE="$(mktemp)"
-    ls -al /projects/huntington_A0/Work/jla | tee --append "${TMPFILE}"
-    hg --repository ~/myco/firmwaresrc parents | tee --append "${TMPFILE}"
-    hg --repository ~/myco/firmwaresrc diff | tee --append "${TMPFILE}"
-
-
-    COSIM_IDENTITY="$1"
-    RUN_VARIANT="$2"
-
-    echo 'cosim identity:' "$COSIM_IDENTITY"
-    echo 'run variant   :' "$RUN_VARIANT"
-
-    export COSIM_IDENTITY
+#     TMPFILE="$(mktemp)"
+#     ls -al /projects/huntington_A0/Work/jla | tee --append "${TMPFILE}"
+#     hg --repository ~/myco/firmwaresrc parents | tee --append "${TMPFILE}"
+#     hg --repository ~/myco/firmwaresrc diff | tee --append "${TMPFILE}"
 
 
+#     COSIM_IDENTITY="$1"
+#     RUN_VARIANT="$2"
 
-    COMMAND="time $HOME/myco/chip_test/src/tools/cosim/esnap "
+#     echo 'cosim identity:' "$COSIM_IDENTITY"
+#     echo 'run variant   :' "$RUN_VARIANT"
 
-    # standard configuration for jlahacks
-    if   [ "$RUN_VARIANT" == 'hacks' ] ; then 
-        COMMAND="$COMMAND --farmi-lite --mccmdline hacks"
-    elif   [ "$RUN_VARIANT" == 'hackswithfsdb' ] ; then 
-        COMMAND="$COMMAND --farmi-lite --simv-args 'FSDB=1' --mccmdline hackswithfsdb"
-    # various combinations of speedups for snapper trivial
-    elif   [ "$RUN_VARIANT" == 'vanilla' ] ; then 
-        COMMAND="$COMMAND --farmi-lite --dutcfg min"
-    elif [ "$RUN_VARIANT" == 'lean' ] ; then
-        COMMAND="$COMMAND --farmi-lite --dutcfg min --lean "
-    elif [ "$RUN_VARIANT" == 'fullyhacked' ] ; then
-        COMMAND="$COMMAND --farmi-lite --dutcfg min --lean --simv-args 'MC_TLP_HACK=1' "
-    # and then those speedups with fsdb files being generated (takes twice the time to run)
-    elif [ "$RUN_VARIANT" == 'vanillawithfsdb' ] ; then
-        COMMAND="$COMMAND --farmi-lite --dutcfg min --simv-args 'FSDB=1'  "
-    elif [ "$RUN_VARIANT" == 'leanwithfsdb' ] ; then
-        COMMAND="$COMMAND --farmi-lite --dutcfg min --lean --simv-args 'FSDB=1'  "
-    elif [ "$RUN_VARIANT" == 'fullyhackedwithfsdb' ] ; then
-        COMMAND="$COMMAND --farmi-lite --dutcfg min --lean --simv-args 'MC_TLP_HACK=1 FSDB=1'"
-    else
-        echo "oops"
-        return
-    fi
+#     export COSIM_IDENTITY
 
-    #
-    COMMAND="$COMMAND trivial"
 
-    echo $COMMAND
-    eval "$COMMAND"
-    esnap_return_value=$?
-    echo "return value " $esnap_return_value
 
-    INFOFILE="/local/scratch/esnap_${COSIM_IDENTITY}/jlainfo" 
-    echo "writing status info from start of run (${TMPFILE}) into scratch directory as ${INFOFILE}"
-    cp "${TMPFILE}" "${INFOFILE}"
+#     COMMAND="time $HOME/myco/chip_test/src/tools/cosim/esnap "
 
-    echo "to back up these results use: backupresults ${COSIM_IDENTITY}  ${RUN_VARIANT}"
-    return $esnap_return_value
-}
+#     # standard configuration for jlahacks
+#     if   [ "$RUN_VARIANT" == 'hacks' ] ; then 
+#         COMMAND="$COMMAND --farmi-lite --mccmdline hacks"
+#     elif   [ "$RUN_VARIANT" == 'hackswithfsdb' ] ; then 
+#         COMMAND="$COMMAND --farmi-lite --simv-args 'FSDB=1' --mccmdline hackswithfsdb"
+#     # various combinations of speedups for snapper trivial
+#     elif   [ "$RUN_VARIANT" == 'vanilla' ] ; then 
+#         COMMAND="$COMMAND --farmi-lite --dutcfg min"
+#     elif [ "$RUN_VARIANT" == 'lean' ] ; then
+#         COMMAND="$COMMAND --farmi-lite --dutcfg min --lean "
+#     elif [ "$RUN_VARIANT" == 'fullyhacked' ] ; then
+#         COMMAND="$COMMAND --farmi-lite --dutcfg min --lean --simv-args 'MC_TLP_HACK=1' "
+#     # and then those speedups with fsdb files being generated (takes twice the time to run)
+#     elif [ "$RUN_VARIANT" == 'vanillawithfsdb' ] ; then
+#         COMMAND="$COMMAND --farmi-lite --dutcfg min --simv-args 'FSDB=1'  "
+#     elif [ "$RUN_VARIANT" == 'leanwithfsdb' ] ; then
+#         COMMAND="$COMMAND --farmi-lite --dutcfg min --lean --simv-args 'FSDB=1'  "
+#     elif [ "$RUN_VARIANT" == 'fullyhackedwithfsdb' ] ; then
+#         COMMAND="$COMMAND --farmi-lite --dutcfg min --lean --simv-args 'MC_TLP_HACK=1 FSDB=1'"
+#     else
+#         echo "oops"
+#         return
+#     fi
 
-alias sim1='onerunsimtorulethemall jla  hacks'
-alias sim2='onerunsimtorulethemall jla2 hacks'
-alias sim3='onerunsimtorulethemall jla3 hacks'
-alias sim4='onerunsimtorulethemall jla4 hacks'
+#     #
+#     COMMAND="$COMMAND trivial"
 
-alias fsim1='onerunsimtorulethemall jla   hackswithfsdb'
-alias fsim2='onerunsimtorulethemall jla2  hackswithfsdb'
-alias fsim3='onerunsimtorulethemall jla3  hackswithfsdb'
-alias fsim4='onerunsimtorulethemall jla4  hackswithfsdb'
+#     echo $COMMAND
+#     eval "$COMMAND"
+#     esnap_return_value=$?
+#     echo "return value " $esnap_return_value
+
+#     INFOFILE="/local/scratch/esnap_${COSIM_IDENTITY}/jlainfo" 
+#     echo "writing status info from start of run (${TMPFILE}) into scratch directory as ${INFOFILE}"
+#     cp "${TMPFILE}" "${INFOFILE}"
+
+#     echo "to back up these results use: backupresults ${COSIM_IDENTITY}  ${RUN_VARIANT}"
+#     return $esnap_return_value
+# }
+
+# alias sim1='onerunsimtorulethemall jla  hacks'
+# alias sim2='onerunsimtorulethemall jla2 hacks'
+# alias sim3='onerunsimtorulethemall jla3 hacks'
+# alias sim4='onerunsimtorulethemall jla4 hacks'
+
+# alias fsim1='onerunsimtorulethemall jla   hackswithfsdb'
+# alias fsim2='onerunsimtorulethemall jla2  hackswithfsdb'
+# alias fsim3='onerunsimtorulethemall jla3  hackswithfsdb'
+# alias fsim4='onerunsimtorulethemall jla4  hackswithfsdb'
 
 alias sbsx='source ~/.bashrc && set -x'
 alias ll='ls -alrt'
 alias e='emacsclient -n'
 alias gitkall='git fsck --lost-found | awk "{ print \$3 ; }" | xargs gitk --all'
 
-alias cdhc='pushd ~/hobby-code'
-alias cdhw='pushd /projects/huntington_A0/Work/jla'
-alias cdfw='pushd ~/myco/firmwaresrc/'
-alias cdct='pushd ~/myco/chip_test'
-alias cdsf='pushd ~/Desktop/solarflare'
-alias cdgs='pushd /projects/huntington_A0/Work/jla/gitsvnhunt'
+# alias cdhc='pushd ~/hobby-code'
+# alias cdhw='pushd /projects/huntington_A0/Work/jla'
+# alias cdfw='pushd ~/myco/firmwaresrc/'
+# alias cdct='pushd ~/myco/chip_test'
+# alias cdsf='pushd ~/Desktop/solarflare'
+# alias cdgs='pushd /projects/huntington_A0/Work/jla/gitsvnhunt'
 
-alias fwtags='pushd ~/myco/firmwaresrc/ && mktags ; popd'
-alias remake='ssh -X anvil "make -j -C ~/myco/firmwaresrc world"'
-alias build_from_clean='ssh -X anvil "make -C ~/myco/firmwaresrc clean world"'
+# alias fwtags='pushd ~/myco/firmwaresrc/ && mktags ; popd'
+# alias remake='ssh -X anvil "make -j -C ~/myco/firmwaresrc world"'
+# alias build_from_clean='ssh -X anvil "make -C ~/myco/firmwaresrc clean world"'
 
-function hgfw { hgtk --repository ~/myco/firmwaresrc log & disown ; } 
+# function hgfw { hgtk --repository ~/myco/firmwaresrc log & disown ; } 
 
 # end of stuff added for solarflare
 
-### Added by the Heroku Toolbelt
-export PATH="/usr/local/heroku/bin:$PATH"
